"""
MTS Kimya - Template Field Name Mapping (English → Turkish)
Used by all CSV generation scripts to produce Turkish-readable field summaries.
Covers all 603 unique template fields across 24 product categories.
"""

FIELD_TR = {
    # --- Abrasive / Polish ---
    "abrasive_type": "Aşındırıcı Tipi",
    "abrasiveness": "Aşındırıcılık",
    "cut_level": "Kesme Gücü",
    "finish_level": "Parlaklık Seviyesi",
    "finish_type": "Bitiriş Tipi",
    "gloss_level": "Parlaklık",
    "gloss_enhancer": "Parlaklık Artırıcı",
    "wipe_off_ease": "Silme Kolaylığı",
    "working_time": "Çalışma Süresi",
    "dusting_level": "Tozuma Seviyesi",
    "grit_removal": "Zımpara İzi Giderme",
    "silicone_free": "Silikon İçermez",
    "filler_free": "Dolgu İçermez",
    "bodyshop_safe": "Boya Atölyesi Uyumlu",
    "safe_for_soft_paint": "Yumuşak Boya İçin Güvenli",
    "contains_protection": "Koruma İçerir",
    "protection_type": "Koruma Tipi",
    "formula_base": "Formül Bazı",
    "recommended_pad_types": "Önerilen Ped Tipleri",

    # --- General Product Info ---
    "volume_ml": "Hacim (ml)",
    "volume_lt": "Hacim (lt)",
    "volume_liters": "Hacim (lt)",
    "volume_kg": "Ağırlık (kg)",
    "volume": "Hacim",
    "weight_kg": "Ağırlık (kg)",
    "weight_g": "Ağırlık (g)",
    "weight_gr": "Ağırlık (g)",
    "weight_net_g": "Net Ağırlık (g)",
    "weight_net_kg": "Net Ağırlık (kg)",
    "weight": "Ağırlık",
    "made_in": "Üretim Ülkesi",
    "color": "Renk",
    "color_code": "Renk Kodu",
    "material": "Malzeme",
    "material_blend": "Malzeme Karışımı",
    "design": "Tasarım",
    "form": "Form",
    "format": "Format",
    "type": "Tip",
    "function": "Fonksiyon",
    "features": "Özellikler",
    "scent": "Koku",
    "scented": "Kokulu",
    "dimensions": "Boyutlar",
    "dimensions_mm": "Boyutlar (mm)",
    "dimensions_cm": "Boyutlar (cm)",
    "dimensions_inch": "Boyutlar (inch)",
    "dimensions_folded_mm": "Katlanmış Boyut (mm)",
    "dimensions_open_mm": "Açık Boyut (mm)",
    "size": "Boyut",
    "quantity": "Adet",
    "pack_quantity": "Paket İçeriği",
    "kit_contents": "Set İçeriği",
    "kit_included": "Set Dahil",
    "origin": "Menşei",
    "sub_type": "Alt Tip",

    # --- Car Shampoo ---
    "ph_level": "pH Seviyesi",
    "ph_label": "pH Etiketi",
    "ph_neutral": "pH Nötr",
    "concentrate": "Konsantre",
    "dilution_ratio": "Seyreltme Oranı",
    "dilution": "Seyreltme",
    "dilution_range": "Seyreltme Aralığı",
    "dilution_foam_lance": "Foam Lance Seyreltme",
    "dilution_kova": "Kova Seyreltme",
    "dilution_heavy": "Yoğun Seyreltme",
    "dilution_light": "Hafif Seyreltme",
    "dilution_prewash": "Ön Yıkama Seyreltme",
    "dilution_manual": "Manuel Seyreltme",
    "dilution_pump": "Pompa Seyreltme",
    "dilution_body": "Gövde Seyreltme",
    "dilution_motor": "Motor Seyreltme",
    "dilution_truck": "Kamyon Seyreltme",
    "dilution_spot": "Spot Seyreltme",
    "dilution_bug_cleaner": "Böcek Temizleme Seyreltme",
    "dilution_maintenance": "Bakım Seyreltme",
    "dilution_decon": "Dekontaminasyon Seyreltme",
    "dilution_dosatron": "Dosatron Seyreltme",
    "dilution_option": "Seyreltme Seçeneği",
    "dilution_scale": "Seyreltme Ölçeği",
    "dilution_steps": "Seyreltme Adımları",
    "dilution_steps_ml": "Seyreltme Adımları (ml)",
    "foam_level": "Köpük Seviyesi",
    "foam_power": "Köpük Gücü",
    "foam_performance": "Köpük Performansı",
    "foam_thickness": "Köpük Kalınlığı",
    "foam_type": "Köpük Tipi",
    "foam_color": "Köpük Rengi",
    "foam_density_adjustable": "Köpük Yoğunluğu Ayarlı",
    "foam_adjustable": "Köpük Ayarlı",
    "foam_levels": "Köpük Seviyeleri",
    "foam_heads": "Köpük Başlıkları",
    "foam_types": "Köpük Tipleri",
    "lubricity_level": "Kayganlık Seviyesi",
    "safe_on_ceramic_coatings": "Seramik Kaplama Uyumlu",
    "safe_on_ppf_wrap": "PPF/Wrap Uyumlu",
    "safe_on_ppf": "PPF Uyumlu",
    "safe_on_paint": "Boya Üzerinde Güvenli",
    "safe_on_plastic": "Plastik Üzerinde Güvenli",
    "safe_on_screens": "Ekranlarda Güvenli",
    "safe_on_tint": "Cam Filmi Güvenli",
    "contains_sio2_or_wax": "SiO2/Wax İçerir",
    "contains_sio2": "SiO2 İçerir",
    "contains_wax": "Wax İçerir",
    "contains_carnauba": "Carnauba İçerir",
    "contains_fluorine": "Flüor İçerir",
    "consumption_ml_per_car": "Tüketim (ml/araç)",
    "consumption_ml_per_wash": "Tüketim (ml/yıkama)",
    "consumption_ml_per_liter": "Tüketim (ml/lt)",
    "consumption_ml_per_liter_hand": "El Yıkama Tüketimi (ml/lt)",
    "consumption_ml_per_kg_machine": "Makine Tüketimi (ml/kg)",
    "consumption_per_car_g": "Tüketim (g/araç)",
    "consumption_ml_per_panel": "Tüketim (ml/panel)",
    "consumption_ml_per_sqm": "Tüketim (ml/m²)",
    "consumption_ml_per_vehicle": "Tüketim (ml/araç)",
    "consumption_ml_per_cabin": "Tüketim (ml/kabin)",
    "consumption_ml_per_wheel_set": "Tüketim (ml/jant seti)",
    "consumption_ml": "Tüketim (ml)",
    "consumption": "Tüketim",
    "consumption_exterior": "Dış Yüzey Tüketimi",
    "consumption_interior": "İç Yüzey Tüketimi",
    "application_method": "Uygulama Yöntemi",
    "application": "Uygulama",
    "application_area": "Uygulama Alanı",
    "application_type": "Uygulama Tipi",
    "application_surface": "Uygulama Yüzeyi",
    "applications_per_bottle": "Şişe Başına Uygulama",
    "washes_per_bottle": "Şişe Başına Yıkama",
    "biodegradable": "Biyoçözünür",
    "biodegradable_surfactants": "Biyoçözünür Yüzey Aktif",
    "eco_friendly": "Çevre Dostu",
    "touchless_cleaning": "Temassız Temizlik",
    "hand_wash": "El Yıkama",
    "machine_wash": "Makine Yıkama",
    "iron_remover": "Demir Tozu Çözücü",
    "bug_remover": "Böcek Çözücü",
    "lime_remover": "Kireç Çözücü",
    "mineral_remover": "Mineral Çözücü",
    "grease_remover": "Yağ Çözücü",
    "soot_remover": "Kurum Çözücü",
    "black_streak_remover": "Siyah İz Çözücü",
    "diesel_remover": "Dizel Çözücü",
    "stripping_power": "Soyma Gücü",
    "cleaning_power": "Temizlik Gücü",
    "cleaning_strength": "Temizlik Gücü",
    "heavy_duty": "Ağır Hizmet",
    "industrial_grade": "Endüstriyel Kalite",
    "hydrophobic": "Su İtici",
    "hydrophobic_effect": "Hidrofobi Etkisi",
    "hydrophobic_level": "Hidrofobi Seviyesi",
    "hydrophobic_restore": "Hidrofobi Yenileme",
    "hydrophobicity_level": "Hidrofobi Seviyesi",
    "coating_restorer": "Kaplama Yenileyici",
    "coating_safe": "Kaplama Uyumlu",
    "wash_and_wax": "Yıka ve Cila",
    "wax_content": "Wax İçeriği",
    "wax_free": "Wax İçermez",
    "cure_time": "Kürleme Süresi",
    "cure_time_hours": "Kürleme Süresi (saat)",
    "cure_time_minutes": "Kürleme Süresi (dk)",
    "curing_time": "Kürleme Süresi",
    "dwell_time_min": "Bekleme Süresi (dk)",
    "dwell_time_minutes": "Bekleme Süresi (dk)",
    "dwell_time_sec": "Bekleme Süresi (sn)",
    "dwell_time_seconds": "Bekleme Süresi (sn)",
    "wait_time_seconds": "Bekleme Süresi (sn)",
    "durability": "Dayanıklılık",
    "durability_months": "Dayanıklılık (ay)",
    "durability_weeks": "Dayanıklılık (hafta)",
    "durability_days": "Dayanıklılık (gün)",
    "durability_days_max": "Maks Dayanıklılık (gün)",
    "durability_months_single": "Tek Kat Dayanıklılık (ay)",
    "durability_months_with_maintenance": "Bakımlı Dayanıklılık (ay)",
    "durability_washes": "Dayanıklılık (yıkama)",
    "durability_km": "Dayanıklılık (km)",
    "durability_label": "Dayanıklılık",
    "duration": "Süre",
    "effect_duration_months": "Etki Süresi (ay)",
    "antistatic": "Antistatik",
    "antistatic_effect": "Antistatik Etki",
    "anti_static": "Antistatik",
    "antistatik": "Antistatik",
    "fragrance_free": "Kokusuz",
    "dye_free": "Boyasız",
    "bleach_free": "Çamaşır Suyu İçermez",
    "naoh_free": "NaOH İçermez",
    "phosphorus_free": "Fosfor İçermez",
    "phosphate_free": "Fosfat İçermez",
    "edta_free": "EDTA İçermez",
    "nta_free": "NTA İçermez",
    "ammonia_free": "Amonyak İçermez",
    "softener_free": "Yumuşatıcı İçermez",
    "acid_free": "Asitsiz",
    "alcohol_free": "Alkolsüz",
    "solvent_free": "Çözücüsüz",
    "voc_free": "VOC İçermez",
    "voc_content": "VOC İçeriği",
    "plant_based_surfactants": "Bitkisel Yüzey Aktif",
    "moisturizing_agents": "Nemlendirici",
    "protective_shield": "Koruyucu Kalkan",
    "aluminum_safe": "Alüminyum Güvenli",
    "plastic_safe": "Plastik Güvenli",
    "plexiglass_safe": "Pleksiglas Güvenli",
    "fiberglass_safe": "Fiberglas Güvenli",
    "tarpaulin_safe": "Branda Güvenli",
    "matte_safe": "Mat Yüzey Güvenli",
    "mat_safe": "Mat Yüzey Güvenli",
    "ppf_safe": "PPF Güvenli",
    "max_spin_rpm": "Maks Devir (rpm)",
    "max_wash_temp": "Maks Yıkama Sıcaklığı",
    "recommended_bucket_ml": "Kova Önerisi (ml)",
    "recommended_foam_cannon_ratio": "Foam Cannon Oranı",
    "self_service_ml_per_car": "Self-Servis (ml/araç)",
    "automatic_ml_per_car": "Otomatik (ml/araç)",
    "rinseless_dilution": "Durulamasız Seyreltme",
    "waterless_dilution": "Susuz Seyreltme",
    "dry_aid_dilution": "Kurulama Yardımcı Seyreltme",
    "alkali_neutralizer": "Alkali Nötrleştirici",
    "alkaline_neutralizer": "Alkali Nötrleştirici",
    "instant_action": "Anında Etki",
    "low_foam": "Düşük Köpük",
    "hard_water_resistant": "Sert Suya Dayanıklı",
    "brushless": "Fırçasız",

    # --- Ceramic Coatings ---
    "sio2_content": "SiO2 İçeriği",
    "sio2_content_percent": "SiO2 İçeriği (%)",
    "sio2_percent": "SiO2 (%)",
    "sio2_percentage": "SiO2 Yüzdesi",
    "layer_count": "Kat Sayısı",
    "layer_thickness_nm": "Kat Kalınlığı (nm)",
    "layering_allowed": "Kat Üstüne Uygulama",
    "contact_angle": "Temas Açısı",
    "hardness": "Sertlik",
    "self_healing": "Kendini Onarma",
    "shrinkage": "Büzüşme",
    "ph_resistance": "pH Dayanımı",
    "ph_tolerance": "pH Toleransı",
    "heat_resistance": "Isı Dayanımı",
    "multi_surface": "Çoklu Yüzey",
    "prep_required": "Ön Hazırlık Gerekli",
    "no_water_hours": "Su Yok (saat)",
    "ipa_content": "IPA İçeriği",
    "ipa_ratio_percent": "IPA Oranı (%)",
    "coverage_ml_per_sqm": "Kaplama (ml/m²)",
    "speed_threshold": "Hız Eşiği",
    "recommended_temperature_c": "Önerilen Sıcaklık (°C)",
    "formula": "Formül",
    "composition": "Bileşim",
    "note": "Not",
    "alcohol_tolerant": "Alkole Dayanıklı",
    "irl_safe": "IRL Güvenli",

    # --- Paint Protection (Quick) ---
    "surface_state": "Yüzey Durumu",
    "finish_effect": "Bitiriş Etkisi",
    "base_type": "Baz Tipi",
    "uv_active": "UV Aktif",
    "uv_protection": "UV Koruması",
    "uv_resistance": "UV Dayanımı",
    "needs_buffing": "Parlatma Gerekli",
    "needs_rinse": "Durulama Gerekli",
    "needs_agitation": "Mekanik Müdahale Gerekli",
    "waterless_wash_capability": "Susuz Yıkama Özelliği",
    "osmosis_compatible": "Osmoz Su Uyumlu",
    "compatible_with_ceramic_coatings": "Seramik Kaplama Uyumlu",
    "sileceksiz_hiz_kmh": "Sileceksiz Hız (km/h)",
    "temp_range_c": "Sıcaklık Aralığı (°C)",

    # --- Clay Products ---
    "clay_form": "Kil Formu",
    "grade": "Agresiflik Seviyesi",
    "reusable": "Yeniden Kullanılabilir",
    "machine_compatible": "Makine Uyumlu",
    "machine_compatibility": "Makine Uyumluluğu",
    "lubricant_required": "Kaydırıcı Gerekli",
    "compatible_with": "Uyumlu",
    "body": "Gövde",
    "attachment": "Bağlantı",

    # --- Microfiber ---
    "gsm": "Gramaj (GSM)",
    "absorption_capacity": "Emicilik Kapasitesi",
    "absorption_level": "Emicilik Seviyesi",
    "pile_type": "Tüy Tipi",
    "edge_type": "Kenar Tipi",
    "dual_sided": "Çift Taraflı",
    "wash_instructions": "Yıkama Talimatı",
    "wash_temp_max": "Maks Yıkama Sıcaklığı",
    "ccs_system": "CCS Sistemi",
    "ccs_technology": "CCS Teknolojisi",
    "inner_sponge_mm": "İç Sünger (mm)",
    "chemical_resistance": "Kimyasal Dayanım",
    "chemical_resistant": "Kimyasala Dayanıklı",

    # --- Polishing Pad ---
    "diameter_mm": "Çap (mm)",
    "thickness_mm": "Kalınlık (mm)",
    "height_mm": "Yükseklik (mm)",
    "hook_and_loop": "Cırtlı",
    "foam_interface": "Köpük Arakatman",
    "cell_structure": "Hücre Yapısı",
    "aggressive": "Agresiflik",
    "short_pile": "Kısa Tüy",
    "safety_edge": "Güvenlik Kenarı",
    "washable": "Yıkanabilir",
    "wool_grade": "Yün Kalitesi",

    # --- Polisher Machine ---
    "power_watt": "Güç (W)",
    "power_output_watt": "Çıkış Gücü (W)",
    "power_w": "Güç (W)",
    "power_watt_or_voltage": "Güç (W/V)",
    "power": "Güç",
    "orbit_mm": "Orbit (mm)",
    "orbit_options_mm": "Orbit Seçenekleri (mm)",
    "rpm": "Devir (rpm)",
    "rotation_speed_rpm": "Dönüş Hızı (rpm)",
    "oscillation_speed_rpm": "Salınım Hızı (rpm)",
    "speed_range": "Hız Aralığı",
    "speed_range_rpm": "Hız Aralığı (rpm)",
    "speed_levels": "Hız Kademeleri",
    "max_speed_rpm": "Maks Hız (rpm)",
    "max_torque_nm": "Maks Tork (Nm)",
    "motor_type": "Motor Tipi",
    "cable_length_m": "Kablo Uzunluğu (m)",
    "battery_type": "Pil Tipi",
    "battery_capacity_ah": "Pil Kapasitesi (Ah)",
    "battery_count": "Pil Sayısı",
    "battery_included": "Pil Dahil",
    "charge_time_minutes": "Şarj Süresi (dk)",
    "charger_included": "Şarj Aleti Dahil",
    "runtime_minutes": "Çalışma Süresi (dk)",
    "runtime_hours": "Çalışma Süresi (saat)",
    "runtime_max_hours": "Maks Çalışma Süresi (saat)",
    "runtime_min": "Min Çalışma Süresi",
    "backing_plate_diameter_mm": "Taban Plakası Çapı (mm)",
    "backing_plate_supported_mm": "Desteklenen Taban (mm)",
    "base_diameter_mm": "Taban Çapı (mm)",
    "surface_diameter_mm": "Yüzey Çapı (mm)",
    "max_pad_diameter_mm": "Maks Ped Çapı (mm)",
    "sanding_pad_size_mm": "Zımpara Ped Çapı (mm)",
    "spindle_thread": "Mil Dişi",
    "accessory_count": "Aksesuar Sayısı",
    "accessory_type": "Aksesuar Tipi",
    "pad_type": "Ped Tipi",
    "compatible_machine": "Uyumlu Makine",
    "nozzle_type": "Nozül Tipi",
    "working_pressure_bar": "Çalışma Basıncı (bar)",
    "working_pressure_psi": "Çalışma Basıncı (psi)",
    "air_pressure_bar": "Hava Basıncı (bar)",
    "air_pressure_psi": "Hava Basıncı (psi)",
    "airflow_l_min": "Hava Akışı (L/dk)",
    "airflow_levels": "Hava Akışı Kademeleri",
    "max_pressure_bar": "Maks Basınç (bar)",
    "max_pressure_psi": "Maks Basınç (psi)",
    "temperature_range_c": "Sıcaklık Aralığı (°C)",
    "temperature_step_c": "Sıcaklık Adımı (°C)",
    "shaft_length_cm": "Mil Uzunluğu (cm)",
    "tank_capacity_ml": "Tank Kapasitesi (ml)",
    "voltage": "Voltaj",
    "power_source": "Güç Kaynağı",
    "product_type": "Ürün Tipi",
    "shape": "Şekil",

    # --- Brushes ---
    "bristle_material": "Kıl Malzemesi",
    "bristle_spec": "Kıl Özellikleri",
    "bristle_type": "Kıl Tipi",
    "bristle_types": "Kıl Tipleri",
    "brush_size": "Fırça Boyutu",
    "brush_type": "Fırça Tipi",
    "handle_design": "Sap Tasarımı",
    "handle_length": "Sap Uzunluğu",
    "handle_length_cm": "Sap Uzunluğu (cm)",
    "handle_material": "Sap Malzemesi",
    "flexibility": "Esneklik",
    "set_content": "Set İçeriği",
    "set_count": "Set Adedi",

    # --- Masking Tapes ---
    "adhesive_type": "Yapışkan Tipi",
    "tape_type": "Bant Tipi",
    "tape_color": "Bant Rengi",
    "width": "Genişlik",
    "width_mm": "Genişlik (mm)",
    "length": "Uzunluk",
    "length_m": "Uzunluk (m)",
    "total_length": "Toplam Uzunluk",
    "temperature_resistance": "Sıcaklık Dayanımı",
    "temperature_resistance_c": "Sıcaklık Dayanımı (°C)",
    "heat_resistant": "Isıya Dayanıklı",
    "residue_free": "Artık Bırakmaz",
    "tear_resistant": "Yırtılmaya Dayanıklı",
    "water_resistant": "Suya Dayanıklı",
    "wet_sanding_safe": "Islak Zımpara Güvenli",
    "transparent_appearance": "Şeffaf Görünüm",
    "pre_cut": "Ön Kesilmiş",

    # --- Fragrance ---
    "fragrance_type": "Koku Tipi",
    "active_ingredient": "Aktif Madde",
    "collection": "Koleksiyon",
    "final_scent": "Son Koku",
    "patent_no": "Patent No",
    "compatible_product": "Uyumlu Ürün",
    "total_uses": "Toplam Kullanım",
    "uses_per_capsule": "Kapsül Başına Kullanım",
    "coverage_per_pad": "Ped Başına Kaplama",
    "child_pet_safe": "Çocuk/Evcil Hayvan Güvenli",
    "vegan": "Vegan",
    "toxic_free": "Toksik İçermez",
    "notes": "Notlar",
    "certifications": "Sertifikalar",

    # --- Interior Cleaner ---
    "alcohol_based": "Alkol Bazlı",
    "alcohol_content": "Alkol İçeriği",
    "anti_bacterial": "Antibakteriyel",
    "anti_bacterial_claim": "Antibakteriyel Özellik",
    "anti_mold": "Küf Önleyici",
    "anti_aging": "Yaşlanma Önleyici",
    "anti_corrosive": "Korozyon Önleyici",
    "breathable": "Nefes Alabilir",
    "enzyme_formula": "Enzim Formülü",
    "extraction_compatible": "Ekstraksiyon Uyumlu",
    "fast_drying": "Hızlı Kuruma",
    "drying_time": "Kuruma Süresi",
    "nanotechnology": "Nanoteknoloji",
    "odor_eliminator": "Koku Giderici",
    "oil_repellent": "Yağ İtici",
    "water_repellent": "Su İtici",
    "coverage": "Kaplama Alanı",
    "coverage_m2": "Kaplama Alanı (m²)",
    "professional_only": "Sadece Profesyonel",
    "working_temp": "Çalışma Sıcaklığı",
    "working_temp_c": "Çalışma Sıcaklığı (°C)",
    "compatible_equipment": "Uyumlu Ekipman",
    "dissolving_temp": "Çözünme Sıcaklığı",
    "siloxane_content": "Siloksan İçeriği",
    "rinse_required": "Durulama Gerekli",
    "protection_duration": "Koruma Süresi",
    "technology": "Teknoloji",

    # --- Leather Care ---
    "suitable_surface": "Uygun Yüzey",
    "suitable_surfaces": "Uygun Yüzeyler",

    # --- Glass Cleaner ---
    "streak_free": "İzsiz",
    "portable": "Taşınabilir",
    "requires_pre_cleaning": "Ön Temizlik Gerekli",
    "product_purpose": "Ürün Amacı",
    "safe_surfaces": "Güvenli Yüzeyler",
    "safe_for": "Güvenli",
    "suitable_for": "Uygun",

    # --- Contaminant Solvers ---
    "chemical_base": "Kimyasal Baz",
    "formulation": "Formülasyon",
    "color_indicator": "Renk Göstergesi",
    "reaction_color": "Reaksiyon Rengi",
    "gel_form": "Jel Formu",
    "gel_or_liquid": "Jel veya Sıvı",
    "glass_safe": "Cam Güvenli",
    "compatible_surfaces": "Uyumlu Yüzeyler",
    "safe_on_surfaces": "Güvenli Yüzeyler",
    "target_dirt": "Hedef Kir",
    "odor": "Koku",
    "odor_level": "Koku Seviyesi",
    "slickness": "Kayganlık",
    "warning": "Uyarı",
    "antioksidan_film": "Antioksidan Film",
    "ready_to_use": "Kullanıma Hazır",
    "cars_per_bar": "Araç/Adet",

    # --- Tire Care ---
    "no_sling": "Sıçramaz",
    "non_greasy": "Yağsız",
    "solvent_based": "Çözücü Bazlı",

    # --- Sprayers & Bottles ---
    "body_material": "Gövde Malzemesi",
    "bottle_color": "Şişe Rengi",
    "capacity_ml": "Kapasite (ml)",
    "capacity_liters": "Kapasite (lt)",
    "capacity_lt": "Kapasite (lt)",
    "capacity_total_lt": "Toplam Kapasite (lt)",
    "capacity_usable_lt": "Kullanılabilir Kapasite (lt)",
    "working_capacity_ml": "Çalışma Kapasitesi (ml)",
    "usable_capacity_liters": "Kullanılabilir Kapasite (lt)",
    "connection_type": "Bağlantı Tipi",
    "compatibility": "Uyumluluk",
    "continuous_spray_lock": "Sürekli Sprey Kilidi",
    "content_identification": "İçerik Tanımlama",
    "dosage_marks": "Dozaj İşaretleri",
    "flow_rate": "Akış Hızı",
    "flow_rate_lpm": "Akış Hızı (L/dk)",
    "graduated_scale": "Ölçekli",
    "gun_length_cm": "Tabanca Uzunluğu (cm)",
    "gun_material": "Tabanca Malzemesi",
    "head_color": "Başlık Rengi",
    "head_count": "Başlık Sayısı",
    "hose_length_m": "Hortum Uzunluğu (m)",
    "integrated_funnel": "Entegre Huni",
    "labeling_area": "Etiketleme Alanı",
    "nozzle_adjustable": "Ayarlı Nozül",
    "nozzle_count": "Nozül Sayısı",
    "nozzle_length_cm": "Nozül Uzunluğu (cm)",
    "nozzle_types": "Nozül Tipleri",
    "off_position": "Kapalı Pozisyon",
    "output_per_spray_ml": "Sprey Başına Çıkış (ml)",
    "pressure_bar": "Basınç (bar)",
    "pressure_gauge": "Basınç Göstergesi",
    "pressure_relief_valve": "Basınç Tahliye Valfi",
    "protective_base": "Koruyucu Taban",
    "pump_material": "Pompa Malzemesi",
    "safety_valve": "Güvenlik Valfi",
    "seal_type": "Conta Tipi",
    "shoulder_strap": "Omuz Askısı",
    "spray_360_degree": "360° Sprey",
    "spray_angle_degrees": "Sprey Açısı (°)",
    "spray_pattern_adjustable": "Sprey Desen Ayarlı",
    "spray_modes": "Sprey Modları",
    "suction_tube_material": "Emme Borusu Malzemesi",
    "tank_material": "Tank Malzemesi",
    "tank_wall": "Tank Duvarı",
    "thread_standard": "Diş Standardı",
    "trigger_material": "Tetik Malzemesi",
    "trigger_output_ml": "Tetik Çıkışı (ml)",
    "trigger_pump_volume_cc": "Tetik Pompa Hacmi (cc)",
    "trigger_type": "Tetik Tipi",
    "valve_type": "Valf Tipi",
    "volume_scale": "Hacim Ölçeği",
    "compressed_air_connection": "Basınçlı Hava Bağlantısı",
    "compressor_connection": "Kompresör Bağlantısı",
    "food_safe": "Gıda Güvenli",
    "spare_foam_filters": "Yedek Köpük Filtreleri",
    "spare_seals_included": "Yedek Conta Dahil",
    "storage_capability": "Depolama Özelliği",

    # --- Storage & Accessories ---
    "barrel_size_mm": "Namlu Boyutu (mm)",
    "beam_angle_range": "Işın Açısı Aralığı",
    "belt_length_inch": "Kayış Uzunluğu (inch)",
    "blower_function": "Üfleme Fonksiyonu",
    "color_temperature_k": "Renk Sıcaklığı (K)",
    "color_temperature_levels": "Renk Sıcaklığı Kademeleri",
    "color_temperature_range_k": "Renk Sıcaklığı Aralığı (K)",
    "cri": "CRI (Renk İşleme İndeksi)",
    "filter_area_cm2": "Filtre Alanı (cm²)",
    "foldable": "Katlanabilir",
    "handle": "Tutamak",
    "includes_grit_guard": "Grit Guard Dahil",
    "includes_lid": "Kapak Dahil",
    "ip_rating": "IP Derecesi",
    "leg_strap_inch": "Bacak Kayışı (inch)",
    "lengths_inch": "Uzunluklar (inch)",
    "liquid_capacity_lt": "Sıvı Kapasitesi (lt)",
    "lumen": "Lümen",
    "lumen_levels": "Lümen Kademeleri",
    "lumen_max": "Maks Lümen",
    "max_load_kg": "Maks Yük (kg)",
    "max_load_lbs": "Maks Yük (lbs)",
    "mounting_points": "Montaj Noktaları",
    "pocket_count": "Cep Sayısı",
    "scale_markings": "Ölçek İşaretleri",
    "stackable": "Üst Üste Konabilir",
    "tiers": "Kat Sayısı",
    "total_length_inch": "Toplam Uzunluk (inch)",
    "universal_fit": "Evrensel Uyum",
    "vacuum_pa": "Emme Gücü (Pa)",
    "wall_mountable": "Duvara Monte Edilir",
    "waterproof": "Su Geçirmez",
    "wear_resistant": "Aşınmaya Dayanıklı",
    "wet_dry": "Islak/Kuru",
    "wheeled": "Tekerlekli",
    "height_range_m": "Yükseklik Aralığı (m)",
    "range_m": "Menzil (m)",

    # --- PPF Tools ---
    "angle": "Açı",
    "double_sided": "Çift Taraflı",
    "felt_type": "Keçe Tipi",
    "holding_power": "Tutma Gücü",
    "holding_power_lbs": "Tutma Gücü (lbs)",
    "magnet": "Manyetik",
    "magnet_count": "Mıknatıs Sayısı",
    "storage_box": "Saklama Kutusu",
    "target_application": "Hedef Uygulama",
    "total_pieces": "Toplam Parça",

    # --- Spare Parts ---
    "part_type": "Parça Tipi",
    "attachment_type": "Bağlantı Tipi",
    "compatible_device": "Uyumlu Cihaz",
    "gasket_type": "Conta Tipi",
    "input_voltage": "Giriş Voltajı",
    "output_cc": "Çıkış (cc)",
    "charge_current": "Şarj Akımı",
    "thread_size": "Diş Boyutu",
    "thread_type": "Diş Tipi",

    # --- Product Sets ---
    "set_type": "Set Tipi",
    "piece_count": "Parça Sayısı",
    "contents": "İçerik",
    "total_volume": "Toplam Hacim",
    "target_user": "Hedef Kullanıcı",
    "individual_size": "Bireysel Boyut",
    "category_coverage": "Kategori Kapsamı",

    # --- Marin Products ---
    "base": "Baz",
    "target_use": "Hedef Kullanım",
    "harmful_ingredients_free": "Zararlı Madde İçermez",
    "fit": "Uyum",
    "confidence": "Güven",
    "gap_reason": "Eksiklik Nedeni",
    "source": "Kaynak",
    "premium": "Premium",
    "flagship": "Amiral Gemisi",
    "heat_buildup": "Isı Birikimi",
    "grit_range": "Grit Aralığı",
    "target_material": "Hedef Malzeme",

    # --- Industrial Products ---
    "cationic_formula": "Katyonik Formül",
    "concentration": "Konsantrasyon",
    "dosage": "Dozaj",
    "finish": "Bitiriş",

    # --- Applicators ---
    "ergonomic": "Ergonomik",
    "professional": "Profesyonel",
    "intended_use": "Kullanım Amacı",
    "purpose": "Amaç",
    "version": "Versiyon",
    "chemical_free": "Kimyasalsız",
    "scratch_safe": "Çizik Güvenli",
    "diameter": "Çap",
    "thickness": "Kalınlık",
    "capacity": "Kapasite",
}


def get_turkish_name(field_name: str) -> str:
    """Get Turkish name for a field, fallback to title-cased English name."""
    if field_name in FIELD_TR:
        return FIELD_TR[field_name]
    # Fallback: convert snake_case to Title Case
    return field_name.replace("_", " ").title()


def format_field_value(value) -> str:
    """Format a field value for display in summary text."""
    if isinstance(value, bool):
        return "Evet" if value else "Hayır"
    if isinstance(value, list):
        return ", ".join(str(v) for v in value)
    if isinstance(value, (int, float)):
        return str(value)
    return str(value)


def build_specs_summary(fields: dict) -> str:
    """
    Build a Turkish-readable specs summary from template.fields.
    Format: "Alan Adı: Değer | Alan Adı: Değer | ..."
    """
    parts = []
    for key, value in fields.items():
        if value is None or value == "" or value == []:
            continue
        tr_name = get_turkish_name(key)
        formatted_value = format_field_value(value)
        parts.append(f"{tr_name}: {formatted_value}")
    return " | ".join(parts)
